### ISSUE TITLE
A bug when updating toVisit list

### ISSUE THREAD

**Issue by zhiming-qiu** [EachOneChew/Dijkstra-s-Algorithm#16]
When we explore the neighbors of current node, we wisely decide not to insert duplicate neighbor nodes into `toVisit` list. This however will introduce a bug.

For example, both node `a` and `b` are adjacent to node `c`. Here below is what happens:

1. We explore `a` and add `c` into `toVisit` list. If `a` carries current distance as 5, then `c` would be initialized with current distance `min(5+1, LARGE_NUMBER) = 6`
2. We then explore `b` whose current distance is actually 3, smaller than `a`'s one. `b` intends to insert `c` into `toVisit` list. It will however stop doing so since it would detect `c` is already inserted into the list by `a`. Hence, we miss the chance to update `c`'s current distance to `min(3+1, 6) = 4`

This is what happened in current test case.
```
2          1          2          3          4          5

1          0          1          4(2?)      5          6

2147483647 2147483647 2147483647 5          2147483647 7

9          8          7          6          7          8

10         9          8          7          8          9

11         10         9          8          9          10

12         11         10         9          10         11

13         12         11         10         11         12
```

Take a look at the element in 2nd row, 4th column. Its current distance should be 2 instead of 4. However, since we explore its top neighbor first, we simply ignore it when exploring its left neighbor and hence see this bug.

The solution would be:
1. Find if a node is already in `toVisit` list. If not, simply insert it.
2. Otherwise, check if current exploration could reduce its current distance, If yes, we simply update the node in `toVisit`.

**Comment by zhiming-qiu** [comment]
@EachOneChew  https://github.com/EachOneChew/Dijkstra-s-Algorithm-FEH/blob/master/src/DistanceCalculator.java#L212 is where you could get started. FYI.

**Comment by EachOneChew** [comment]
I can maybe see where the issue is coming from, but (3, 1) having a distance of 4 is intended. This is because located at (2, 1) is an enemy target, and enemies cannot be walked through by the unit. Thus the unit must travel the path of:
(1, 1) -> (1, 0) -> (2, 0) -> (3, 0) -> (3, 1), giving a distance of 4.

Move target4 out of the way (to (4, 4) for example) and the distance of (3, 1) will return to 2.

**Comment by EachOneChew** [comment]
Edit: I don't _think_ there is an issue here. Reasoning is as follows.

Dijkstra's Algorithm runs in such away such that a node is never set as currentNode (and subsequently marked as visited) until all possible shorter paths have already been considered. Thus, if a node has been marked isTraversed, it should never need to have it's currentDistance marked again.

**Comment by zhiming-qiu** [comment]
nice defense.

**Comment by zhiming-qiu** [comment]
👍
